#!/bin/bash

dist=$(grep DISTRIB_ID /etc/*-release | awk -F '=' '{print $2}')

if [ "$dist" == "Ubuntu" ]; then
  echo "Начинаю выполнение"
  paket=apt
  sudo $paket update && sudo $paket upgrade
  sudo $paket install perl
  echo "Обновление выполненно! "
  inst=dpkg

else
  echo "Используется дистрибутив отличный от Ubuntu"
  paket=yum
  sudo $paket update && sudo $paket upgrade
  sudo $paket install perl
  echo "Обновление выполненно! "
  inst=rpm
fi
wget https://store.udv.group/index.php/s/4mBegeErDaC96Mp/download/glpi-agent-UDV.pl
sudo perl glpi-agent-UDV.pl
echo "Начинаю настройку агента"
sudo sed -i '12 s/#server = http://server.domain.com//server = http://glpi.udv.group/' /etc/glpi-agent/agent.cfg
sudo sed -i '16 s/#server = http://server.domain.com//server = http://glpi.udv.group/' /etc/glpi-agent/agent.cfg
sudo sed -i '37 s/3600/120' /etc/glpi-agent/agent.cfg
sudo systemctl enable --now glpi-agent
echo "Завершено!"